#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -I../../../下载/software/lapack-3.4.2/lapacke/include -I../../../下载/software/lapack-3.4.2/CBLAS/include -Iinc
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC) -I../../../下载/software/lapack-3.4.2/CBLAS/src -I../../../下载/software/lapack-3.4.2/SRC
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR) -L../../../下载/software/lapack-3.4.2/CBLAS/lib
LIB_DEBUG = $(LIB)../../../下载/software/lapack-3.4.2/CBLAS/lib/cblas_LINUX.a ../../../下载/software/lapack-3.4.2/liblapacke.a ../../../下载/software/lapack-3.4.2/libtmglib.a ../../../下载/software/lapack-3.4.2/liblapack.a ../../../下载/software/lapack-3.4.2/librefblas.a -lgfortran
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/psat

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/PV.o $(OBJDIR_DEBUG)/src/BoundaryNode.o $(OBJDIR_DEBUG)/src/Bus.o $(OBJDIR_DEBUG)/src/Clpsat.o $(OBJDIR_DEBUG)/src/DAE.o $(OBJDIR_DEBUG)/src/Fault.o $(OBJDIR_DEBUG)/src/Line.o $(OBJDIR_DEBUG)/src/Mn.o $(OBJDIR_DEBUG)/src/PQ.o $(OBJDIR_DEBUG)/src/Psat.o $(OBJDIR_DEBUG)/src/SW.o $(OBJDIR_DEBUG)/src/Settings.o $(OBJDIR_DEBUG)/src/Shunt.o $(OBJDIR_DEBUG)/src/Syn.o $(OBJDIR_DEBUG)/src/Varout.o $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/lib/myLib.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/PV.o $(OBJDIR_RELEASE)/src/BoundaryNode.o $(OBJDIR_RELEASE)/src/Bus.o $(OBJDIR_RELEASE)/src/Clpsat.o $(OBJDIR_RELEASE)/src/DAE.o $(OBJDIR_RELEASE)/src/Fault.o $(OBJDIR_RELEASE)/src/Line.o $(OBJDIR_RELEASE)/src/Mn.o $(OBJDIR_RELEASE)/src/PQ.o $(OBJDIR_RELEASE)/src/Psat.o $(OBJDIR_RELEASE)/src/SW.o $(OBJDIR_RELEASE)/src/Settings.o $(OBJDIR_RELEASE)/src/Shunt.o $(OBJDIR_RELEASE)/src/Syn.o $(OBJDIR_RELEASE)/src/Varout.o $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/lib/myLib.o

all: debug 

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG)/lib || mkdir -p $(OBJDIR_DEBUG)/lib

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/PV.o: src/PV.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/PV.cpp -o $(OBJDIR_DEBUG)/src/PV.o

$(OBJDIR_DEBUG)/src/BoundaryNode.o: src/BoundaryNode.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/BoundaryNode.cpp -o $(OBJDIR_DEBUG)/src/BoundaryNode.o

$(OBJDIR_DEBUG)/src/Bus.o: src/Bus.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Bus.cpp -o $(OBJDIR_DEBUG)/src/Bus.o

$(OBJDIR_DEBUG)/src/Clpsat.o: src/Clpsat.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Clpsat.cpp -o $(OBJDIR_DEBUG)/src/Clpsat.o

$(OBJDIR_DEBUG)/src/DAE.o: src/DAE.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DAE.cpp -o $(OBJDIR_DEBUG)/src/DAE.o

$(OBJDIR_DEBUG)/src/Fault.o: src/Fault.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Fault.cpp -o $(OBJDIR_DEBUG)/src/Fault.o

$(OBJDIR_DEBUG)/src/Line.o: src/Line.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Line.cpp -o $(OBJDIR_DEBUG)/src/Line.o

$(OBJDIR_DEBUG)/src/Mn.o: src/Mn.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Mn.cpp -o $(OBJDIR_DEBUG)/src/Mn.o

$(OBJDIR_DEBUG)/src/PQ.o: src/PQ.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/PQ.cpp -o $(OBJDIR_DEBUG)/src/PQ.o

$(OBJDIR_DEBUG)/src/Psat.o: src/Psat.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Psat.cpp -o $(OBJDIR_DEBUG)/src/Psat.o

$(OBJDIR_DEBUG)/src/SW.o: src/SW.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SW.cpp -o $(OBJDIR_DEBUG)/src/SW.o

$(OBJDIR_DEBUG)/src/Settings.o: src/Settings.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Settings.cpp -o $(OBJDIR_DEBUG)/src/Settings.o

$(OBJDIR_DEBUG)/src/Shunt.o: src/Shunt.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Shunt.cpp -o $(OBJDIR_DEBUG)/src/Shunt.o

$(OBJDIR_DEBUG)/src/Syn.o: src/Syn.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Syn.cpp -o $(OBJDIR_DEBUG)/src/Syn.o

$(OBJDIR_DEBUG)/src/Varout.o: src/Varout.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Varout.cpp -o $(OBJDIR_DEBUG)/src/Varout.o

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/lib/myLib.o: lib/myLib.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/myLib.cpp -o $(OBJDIR_DEBUG)/lib/myLib.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)/lib


.PHONY: before_debug after_debug clean_debug

